const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const targetCanvas=document.getElementById('targetCanvas'),tctx=targetCanvas.getContext('2d');
const els={stage:document.getElementById('stageValue'),score:document.getElementById('scoreValue'),time:document.getElementById('timeValue'),timer:document.getElementById('timerBox'),hints:document.getElementById('hintCount'),hintButton:document.getElementById('hintButton'),targetName:document.getElementById('targetName'),toast:document.getElementById('toast'),ring:document.getElementById('hintRing'),startModal:document.getElementById('startModal'),gameoverModal:document.getElementById('gameoverModal')};
const colors=['#18D89A','#FFD548','#FF6168','#5777F2','#A878EE','#FF9B55','#2FC3D3','#F277B0'];
const types=[{name:'SHARP',pts:[[-.48,.45],[0,-.55],[.48,.45]]},{name:'RIGHT',pts:[[-.5,.48],[-.5,-.5],[.5,.48]]},{name:'WIDE',pts:[[-.56,.32],[0,-.33],[.56,.32]]},{name:'SLIM',pts:[[-.33,.53],[0,-.58],[.33,.53]]},{name:'SCALENE',pts:[[-.52,.45],[-.12,-.54],[.5,.45]]}];
let W=0,H=0,dpr=1,triangles=[],target=null,stage=1,score=0,time=30,hints=3,running=false,last=0,toastTimer,effects=[];
function resize(){const r=canvas.parentElement.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);if(!running&&triangles.length===0) generateDemo();}
function rand(a,b){return a+Math.random()*(b-a)} function pick(a){return a[Math.floor(Math.random()*a.length)]}
function pointsFor(t){const c=Math.cos(t.rot),s=Math.sin(t.rot);return types[t.type].pts.map(([x,y])=>({x:t.x+(x*c-y*s)*t.size,y:t.y+(x*s+y*c)*t.size}))}
function pathTriangle(c,t){const p=pointsFor(t);c.beginPath();c.moveTo(p[0].x,p[0].y);c.lineTo(p[1].x,p[1].y);c.lineTo(p[2].x,p[2].y);c.closePath()}
function drawTriangle(c,t,preview=false){pathTriangle(c,t);c.fillStyle=t.color;c.globalAlpha=t.alpha??.84;c.fill();c.globalAlpha=1;c.strokeStyle=preview?'rgba(23,32,31,.28)':'rgba(23,32,31,.2)';c.lineWidth=preview?2:1.2;c.stroke();if(!preview&&t.pattern){c.save();pathTriangle(c,t);c.clip();c.strokeStyle='rgba(255,255,255,.25)';c.lineWidth=2;for(let n=-t.size;n<t.size*2;n+=11){c.beginPath();c.moveTo(t.x-t.size,n+t.y-t.size);c.lineTo(t.x+t.size,n+t.y);c.stroke()}c.restore()}}
function makeTriangle(i,count,demo=false){const small=Math.max(36,78-stage*3);return{x:rand(25,W-25),y:rand(25,H-25),size:rand(small,small+75),rot:rand(0,Math.PI*2),type:Math.floor(rand(0,types.length)),color:pick(colors),alpha:rand(.58,.9),pattern:stage>3&&Math.random()<.16,dx:stage>4?rand(-5,5):0,dy:stage>4?rand(-5,5):0,dr:stage>4?rand(-.025,.025):0,isTarget:false}}
function generateDemo(){triangles=[];for(let i=0;i<34;i++)triangles.push(makeTriangle(i,34,true));draw()}
function generateStage(){triangles=[];const count=Math.min(42+stage*10,115);for(let i=0;i<count;i++)triangles.push(makeTriangle(i,count));const targetIndex=Math.floor(rand(Math.floor(count*.56),count));target=triangles[targetIndex];target.isTarget=true;target.alpha=.9;target.pattern=false;
  // Keep enough of the target in bounds and give it a likely exposed edge.
  target.x=rand(target.size*.55,W-target.size*.55);target.y=rand(target.size*.55,H-target.size*.55);
  for(let i=targetIndex+1;i<count;i++){const t=triangles[i];if(Math.hypot(t.x-target.x,t.y-target.y)<target.size*.42){t.x+=t.x<target.x?-target.size*.55:target.size*.55;t.y+=t.y<target.y?-target.size*.35:target.size*.35}}
  drawTarget();updateUI();draw();
}
function drawTarget(){tctx.clearRect(0,0,120,82);const p={x:60,y:42,size:66,rot:target.rot,type:target.type,color:target.color,alpha:1};drawTriangle(tctx,p,true);els.targetName.textContent=types[target.type].name}
function draw(){ctx.clearRect(0,0,W,H);for(const t of triangles)drawTriangle(ctx,t);drawEffects()}
function burst(x,y,points){
  effects.push({kind:'ring',x,y,life:1,max:1},{kind:'ring',x,y,life:.78,max:.78,delay:.1});
  for(let i=0;i<54;i++){const a=rand(0,Math.PI*2),speed=rand(110,390);effects.push({kind:i%5===0?'triangle':'confetti',x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed-rand(30,130),rot:rand(0,Math.PI*2),vr:rand(-8,8),size:rand(5,13),color:pick(colors),life:rand(.65,1.15),max:1.15})}
  effects.push({kind:'score',x,y:y-12,text:'+'+points,life:1.05,max:1.05});
  const area=document.getElementById('playArea');area.style.setProperty('--hit-x',x+'px');area.style.setProperty('--hit-y',y+'px');area.classList.remove('success-flash','success-shake');void area.offsetWidth;area.classList.add('success-flash','success-shake');setTimeout(()=>area.classList.remove('success-flash','success-shake'),700);
}
function drawEffects(){for(const e of effects){if(e.delay>0)continue;const p=1-e.life/e.max;ctx.save();if(e.kind==='ring'){ctx.globalAlpha=(1-p)*.9;ctx.strokeStyle=p<.45?'#FFD548':'#18D89A';ctx.lineWidth=7*(1-p)+2;ctx.beginPath();ctx.arc(e.x,e.y,24+p*145,0,Math.PI*2);ctx.stroke()}else if(e.kind==='score'){ctx.globalAlpha=Math.min(1,e.life*3);ctx.translate(e.x,e.y-p*85);ctx.textAlign='center';ctx.lineJoin='round';ctx.font='800 '+(28+p*16)+'px "DM Sans"';ctx.strokeStyle='#fff';ctx.lineWidth=8;ctx.strokeText(e.text,0,0);ctx.fillStyle='#17201f';ctx.fillText(e.text,0,0)}else{ctx.globalAlpha=Math.min(1,e.life*4);ctx.translate(e.x,e.y);ctx.rotate(e.rot);ctx.fillStyle=e.color;if(e.kind==='triangle'){ctx.beginPath();ctx.moveTo(0,-e.size);ctx.lineTo(e.size*.86,e.size*.65);ctx.lineTo(-e.size*.86,e.size*.65);ctx.closePath();ctx.fill()}else{ctx.fillRect(-e.size/2,-e.size/3,e.size,e.size*.66)}}ctx.restore()}}
function updateEffects(dt){for(const e of effects){if(e.delay>0){e.delay-=dt;continue}e.life-=dt;if(e.kind==='confetti'||e.kind==='triangle'){e.vy+=430*dt;e.x+=e.vx*dt;e.y+=e.vy*dt;e.rot+=e.vr*dt;e.vx*=.992}}effects=effects.filter(e=>e.life>0)}
function updateUI(){els.stage.textContent=String(stage).padStart(2,'0');els.score.textContent=String(score).padStart(4,'0');els.time.textContent=Math.max(0,time).toFixed(1);els.timer.classList.toggle('danger',time<=8);els.hints.textContent='× '+hints;els.hintButton.disabled=!running||hints<=0}
function pointInTriangle(px,py,t){const [a,b,c]=pointsFor(t);const s=(a.x-c.x)*(py-c.y)-(a.y-c.y)*(px-c.x),u=(b.x-a.x)*(py-a.y)-(b.y-a.y)*(px-a.x),v=(c.x-b.x)*(py-b.y)-(c.y-b.y)*(px-b.x);return(s<0&&u<0&&v<0)||(s>0&&u>0&&v>0)}
function hitTest(x,y){for(let i=triangles.length-1;i>=0;i--)if(pointInTriangle(x,y,triangles[i]))return triangles[i];return null}
function showToast(text,bad=false){clearTimeout(toastTimer);els.toast.textContent=text;els.toast.className='toast show'+(bad?' bad':'');toastTimer=setTimeout(()=>els.toast.className='toast',900)}
function clickGame(e){if(!running)return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,hit=hitTest(x,y);if(hit===target){const earned=100+stage*25+Math.ceil(time)*2;score+=earned;burst(x,y,earned);stage++;time=Math.min(35,time+4);showToast('PERFECT HUNT!');setTimeout(generateStage,760)}else if(hit){time=Math.max(0,time-3);showToast('MISS  −3 SEC',true);updateUI()}}
function hint(){if(!running||hints<=0)return;hints--;const r=canvas.getBoundingClientRect();els.ring.style.left=(target.x+r.left)+'px';els.ring.style.top=(target.y+r.top)+'px';els.ring.classList.remove('show');void els.ring.offsetWidth;els.ring.classList.add('show');updateUI()}
function animate(now){if(!running)return;const dt=Math.min((now-last)/1000,.05);last=now;time-=dt;updateEffects(dt);if(stage>4){for(const t of triangles){t.rot+=t.dr*dt;t.x+=t.dx*dt;t.y+=t.dy*dt;if(t.x<-30)t.x=W+30;if(t.x>W+30)t.x=-30;if(t.y<-30)t.y=H+30;if(t.y>H+30)t.y=-30}}draw();updateUI();if(time<=0){endGame();return}requestAnimationFrame(animate)}
function startGame(){stage=1;score=0;time=30;hints=3;effects=[];running=true;els.startModal.classList.remove('show');els.gameoverModal.classList.remove('show');generateStage();last=performance.now();requestAnimationFrame(animate)}
function endGame(){running=false;time=0;updateUI();document.getElementById('finalStage').textContent=stage;document.getElementById('finalScore').textContent=score;els.gameoverModal.classList.add('show')}
canvas.addEventListener('click',clickGame);els.hintButton.addEventListener('click',hint);document.getElementById('startButton').addEventListener('click',startGame);document.getElementById('retryButton').addEventListener('click',startGame);addEventListener('resize',resize);resize();
